---
- name: Disable ubuntu login spam
  hosts: sphinx
  tasks:
    - name: remove ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 10-help-text
        - 50-motd-news
        - 80-livepatch
