---
- name: configure restrictive firewall
  hosts: sphinx
  tasks:
  - name: install ufw
    apt: name=ufw
  - name: set up ufw to deny all
    ufw: state=enabled policy=deny
  - name: allow ssh traffic
    ufw: rule=allow name=OpenSSH

- name: disable ipv6 completely
  hosts: sphinx
  tasks:
  - name: Load cmdline content
    slurp:
      src: "/proc/cmdline"
    register: cmdline_data
  - name: Disable IPv6
    template:
      src: disable-ipv6.conf.j2
      dest: /etc/sysctl.d/10-disable-ipv6.conf
    notify: run sysctl
    when: 'not "ipv6.disable=1" in cmdline_data.content|b64decode'
  handlers:
  - name: run sysctl
    command: sysctl --load=/etc/sysctl.d/10-disable-ipv6.conf
