---
- name: prepare encfs and scripts
  hosts: sphinx
  tasks:
    - name: create fuse mount points
      file:
        path: '/mnt/{{ item }}'
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
        - home_decrypted
        - data_decrypted

    - name: create hidrive mount point
      file:
        path: /mnt/home_hidrive_crypted
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: create scripts dir
      file:
        path: /root/scripts
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: write phrase.gpg
      copy:
        dest: /root/scripts/phrase.gpg
        src: files/phrase.gpg.vault
        mode: '0600'
        owner: root
        group: root

    - name: create hidrive mount script (manual mount)
      template:
        src: templates/encfs-hidrive-mount-webdav.sh.j2
        dest: /root/scripts/hidrive-mount-webdav.sh
        group: root
        owner: root
        mode: '0700'

    - name: create unlock script
      template:
        src: templates/encfs-unlock.sh.j2
        dest: /root/scripts/unlock.sh
        group: root
        owner: root
        mode: '0700'

    - name: write hidrive_ssh_key
      copy:
        dest: /root/scripts/hidrive_ssh_key
        src: files/hidrive_ssh_key.vault
        mode: '0600'
        owner: root
        group: root

    - name: create hidrive backup script (for cronjob)
      template:
        src: templates/encfs-backup-to-hidrive.sh.j2
        dest: /root/scripts/backup-to-hidrive.sh
        group: root
        owner: root
        mode: '0700'
