---
- name: serve shares via SMB
  hosts: sphinx
  tasks:
    - name: install SMB packages
      apt: name=samba
    - name: disable autostart for smbd service and stop it if it is running
      service:
        name: smbd
        state: stopped
        enabled: no
    - name: disable autostart for nmbd service and stop it if it is running
      service:
        name: nmbd
        state: stopped
        enabled: no
    - name: allow Samba traffic in firewall
      ufw: rule=allow name=Samba
    - name: configure Samba
      template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        group: root
        owner: root
        mode: '0644'
    - name: configure Samba user map
      template:
        src: templates/smbusers.j2
        dest: /etc/samba/smbusers
        group: root
        owner: root
        mode: '0644'
    - name: configure Samba lmhosts file
      template:
        src: templates/lmhosts.j2
        dest: /etc/samba/lmhosts
        group: root
        owner: root
        mode: '0644'
