---
- name: serve shares via SMB
  hosts: sphinx
  tasks:
    - name: install SMB packages
      apt: name=samba
    - name: disable autostart for smbd service and stop it if it is running
      service:
        name: smbd
        state: stopped
        enabled: no
    - name: disable autostart for nmbd service and stop it if it is running
      service:
        name: nmbd
        state: stopped
        enabled: no
    - name: allow Samba traffic in firewall
      ufw: rule=allow name=Samba

# /etc/samba/smb.conf
# ports: 139 (tcp)
#        445 (tcp)
# nmbd: 137, 138 (udp)

